### ISSUE TITLE
chore(k8s/unwind/grafana): use declarative config

### ISSUE THREAD

**Issue by uhthomas** [uhthomas/automata#199]
Grafana is currently configured through the UI, with lots of dashboards manually added. It would be nice to move this configuration into the Kubernetes manifests and load dashboard directly from grafana.net.

**Comment by onedr0p** [comment]
For any custom dashboards (outside of grafana.net) you can deploy [this](https://github.com/kiwigrid/k8s-sidecar) as a sidecar to grafana and then define your dashboards as a `configmap`. Grafana would then automatically add them in if a certain `.metadata.label` is set on it. It's a poor-mans operator at best but it works. You can see their helm chart for more technical details on how it is done.

**Comment by uhthomas** [comment]
> For any custom dashboards (outside of grafana.net) you can deploy [this](https://github.com/kiwigrid/k8s-sidecar) as a sidecar to grafana and then define your dashboards as a `configmap`. Grafana would then automatically add them in if a certain `.metadata.label` is set on it. It's a poor-mans operator at best but it works. You can see their helm chart for more technical details on how it is done.

This looks cool, thank you. I'll take a look at some point.

**Comment by uhthomas** [comment]
https://github.com/ceph/ceph/tree/main/monitoring/ceph-mixin/dashboards_out

**Comment by uhthomas** [comment]
Fixed in https://github.com/uhthomas/automata/commit/7bf70dad3bd47cfd0206e172cdd4e0a84f74c51c
